server:
  port: 6060
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/TMartDb
    username: postgres
    password: huy123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  prefix: api/v1
jwt:
  expiration: 604800 # 7 days
  secretKey: Danghuy2132@!